### ISSUE TITLE
missing dependencies?

### ISSUE THREAD

**Issue by MatthiasBitterle** [someweisguy/esp_dmx#26]
Good Morning somewiseguy,
I tried too use yore library on an Espresso 32, using the Arduino IDE on a Mac  and included your library via the library manager of Arduino IDE, but I get an error for a missing file:

Arduino: 1.8.19 (Mac OS X), Board: "ESP32 Dev Module, Disabled, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), 240MHz (WiFi/BT), QIO, 80MHz, 4MB (32Mb), 921600, None"

In file included from /Users/Coden/Documents/Arduino/test/test.ino:4:0:
/Users/Coden/Documents/Arduino/libraries/esp_dmx/src/esp_dmx.h:12:28: fatal error: hal/gpio_types.h: No such file or directory
compilation terminated.
exit status 1
Fehler beim Kompilieren für das Board ESP32 Dev Module.

any idea where I can get this file from?

**Comment by someweisguy** [comment]
Thank you for the message. It appears the issue is that the version of Arduino that you are using is unsupported. You must use Arduino-ESP32 v2.0.3 or newer. Follow the instructions on the ESP IDF documentation [here](https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html) to ensure that you are using the latest version of Arduino-ESP32.

Let me know if you have any further questions!
