### ISSUE TITLE
e1.11 devices compatibility with e1.31 data source

### ISSUE THREAD

**Issue by surajchauhan6631** [someweisguy/esp_dmx#38]
As you mention that your library allows for receiving of e1.11 DMX 512 , will it will be able to also receive and decode the e1.31 DMX data because some software transmit e1.31 or SACN data.
or e1.311 is protocol of  with e1.11 standard . please help me as I don't have too much knowledge about it.

**Comment by someweisguy** [comment]
Thanks for the question!

Basically, no. This library does not support E1.31. sACN is an IP protocol. sACN packets are transmitted on IP networks using ethernet cables. E1.11 DMX uses a UART port over RS-485 to transmit data. DMX uses an XLR5 connector instead of ethernet.

You can combine this library with that of another that is designed for transmitting and receiving sACN. [This](https://github.com/forkineye/ESPAsyncE131) library for example can be used with esp_dmx to convert sACN to DMX or vice versa. 

For more in-depth information about ACN, you can read the [E1.31 standards documents](https://webstore.ansi.org/preview-pages/ESTA/preview_ANSI+E1.31-2018.pdf) or if you have other questions I can do my best to answer them!
