### ISSUE TITLE
Compiling Error missing Files

### ISSUE THREAD

**Issue by niko-h** [someweisguy/esp_dmx#76]
Hi,
I get multiple compiling errors about missing files like this one:
```
/src/dmx/types.h:10:10: fatal error: esp_intr_alloc.h: No such file or directory
   10 | #include "esp_intr_alloc.h"
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.

``` 
I tried to fix these by manually finding the missing files in other repositories, but as one after another missing file error pops up, at some point I gave up. The board I am trying to compile for is an ESP 8266 D1.
I reinstalled your project and various versions of it, as well as the Arduino-ESP32 Framework with no success.
Do you have any idea what I'm doing wrong?

**Comment by someweisguy** [comment]
Thanks for reaching out. Unfortunately, this library is not compatible with the ESP8266. It is only compatible with the ESP32 and the 32 family of Espressif microcontrollers. This is because the ESP8266 does not use Arduino-ESP32, but instead uses [Arduino-ESP8266](https://github.com/esp8266/Arduino).

Sorry for the confusion, and hopefully this helps! Let me know if you have any other questions.

**Comment by niko-h** [comment]
Thanks for your reply! I should have payed more attention reading the closed issues. 😅

I will have a look at [DMXSerial](https://github.com/mathertel/DMXSerial).
